import type { ScreenerRow } from "./types";

export const MOCK_SCREENER_DATA: ScreenerRow[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    pe_ratio: 39.99,
    roe: 146.69,
    debt_to_equity: 0.8,
    net_margin: 27.15,
    asset_turnover: 1.25,
    equity_multiplier: 4.31,
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    sector: "Technology",
    pe_ratio: 23.36,
    roe: 33.13,
    debt_to_equity: 0.25,
    net_margin: 39.34,
    asset_turnover: 0.49,
    equity_multiplier: 1.73,
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    pe_ratio: 28.95,
    roe: 26.26,
    debt_to_equity: 0.68,
    net_margin: 21.4,
    asset_turnover: 0.53,
    equity_multiplier: 2.33,
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Incorporated",
    sector: "Healthcare",
    pe_ratio: 14.2,
    roe: 18.6,
    debt_to_equity: 0.72,
    net_margin: 4.2,
    asset_turnover: 1.4,
    equity_multiplier: 3.17,
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    sector: "Financials",
    pe_ratio: 12.4,
    roe: 17.1,
    debt_to_equity: null,
    net_margin: 33.8,
    asset_turnover: 0.08,
    equity_multiplier: null,
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    sector: "Financials",
    pe_ratio: 31.7,
    roe: 51.2,
    debt_to_equity: 0.61,
    net_margin: 54.8,
    asset_turnover: 0.48,
    equity_multiplier: 1.94,
  },
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    sector: "Consumer Staples",
    pe_ratio: 25.1,
    roe: 44.3,
    debt_to_equity: 1.72,
    net_margin: 22.9,
    asset_turnover: 0.56,
    equity_multiplier: 3.46,
  },
  {
    symbol: "PG",
    name: "The Procter & Gamble Company",
    sector: "Consumer Staples",
    pe_ratio: 24.8,
    roe: 32.6,
    debt_to_equity: 0.66,
    net_margin: 18.4,
    asset_turnover: 0.65,
    equity_multiplier: 2.73,
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    sector: "Energy",
    pe_ratio: 13.9,
    roe: 16.8,
    debt_to_equity: 0.19,
    net_margin: 9.1,
    asset_turnover: 0.83,
    equity_multiplier: 2.22,
  },
  {
    symbol: "HON",
    name: "Honeywell International Inc.",
    sector: "Industrials",
    pe_ratio: 22.3,
    roe: 28.4,
    debt_to_equity: 1.15,
    net_margin: 13.2,
    asset_turnover: 0.6,
    equity_multiplier: 3.58,
  },
  {
    symbol: "HD",
    name: "The Home Depot, Inc.",
    sector: "Consumer Discretionary",
    pe_ratio: 24.6,
    roe: null,
    debt_to_equity: null,
    net_margin: 10.1,
    asset_turnover: 1.78,
    equity_multiplier: null,
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    sector: "Communication Services",
    pe_ratio: 18.7,
    roe: 5.9,
    debt_to_equity: 0.42,
    net_margin: 6.8,
    asset_turnover: 0.46,
    equity_multiplier: 1.85,
  },
];
